# Generated by Django 3.1.7 on 2021-03-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=400)),
                ('sound', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('last_word', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('second_last_word', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
